[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "d08a5041ac9fd066fa65f358312fb30f228fce4d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a51e80ff4d5fe456e829d45f43cd04590d5932e60671c91d687091495d72d645"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "63207285d0cdbfa74cba869d22d644707ffd5a44"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "296e2622d8700377607e43976890d789830105f6b900907a420b067ec28d7bef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "700e1f3c0e502ba93abad000e2f7c4ae2a49dd43"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4c8a36aa3f2f53f4afbbb942d59967fce2146267a50a544a46941296705291f2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "6b20032a22fc9da469832a506894bf40afbc122f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f16f4dfd7da6747752dd95d1a4b002f95b5513aee79c70975d924436202aab67"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "3308dd8b86a58e2df9408976bcfa20691ed589de"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3585d0ee73979b1159ee97a9c1dcf541a7a440dc592452092a94e35254dc176b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "f73fccfea45e645711b80f7e734a68bd2250d376"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "252013f687484116e07ffd2e5abd238a22b3b36dbaa9779dcd8fd87ea738dd00"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "48ba0329b71617a2ad51d8d839622377bef31290"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "bc98582c25c39cb25d447a1275b4264e1f2b7147d9a97db37c92fb973ebb2033"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "af57502a298c12d9a1ae5af0b2cd411c65af6213"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "55b6e2255efbfbfe9e0c3a68d03b4d3fa056566660c6f6a2949b622f31230ca9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "b671b149f591b4fb1528a3a8f67409a1c8c27931"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ee472c50e78cd1558d343aaa873ccebe8472b051d75ce56c40b9f340266e9098"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "b94ed2a933a6b6c4efd120b46cd6d90ed294cef6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "26f68109d367874fa4ed20a3c032e9ff3c0cf966ac1f29c696c6d40a85b12985"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "e1a12dde4ae6edea0c02042acf6b24aeded50e67"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "15b8827426cc936e546f457f48f1dbb027552454af4628c9c58117b55e44c20a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "d3482ad4d2e05a5c46d69956fcb315ea25a4698d"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d3087fd04123ca0f6fcd0eea4755a2b88abc01519bc630ba403d43f25b64fe1b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "aa5558f84b0c99adca427c97043a30b931c7c0a0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f71e8ca904638f0c58ceeaa57c092fe90cfa39112499fef4ec493130476bac78"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "2be73f835e176fab05ba58fd353a662d9661a0cc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "78a6b5d40fd1aae58a333b415c082167001879d58a02a7cc772af1725211b6e0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "e0888c4bfd7998de879168e27f19a8ea7c4d10bc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "fd6d48f7253e140f1115f3995b84fb50cd8a1ca46f7d1975b1ea53241c29e69e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "79b189f7de87ab2f70f83401178af8caed9eab8f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "43be5bbf33ce84166f4f19f3890ef6e8411e6326aa3424d1595a3984f4f9418c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "bdcd195f3983f26d23f893e36c8a4ac02f52ee5f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "5230e06be3673f10587b46de0f9e872d030dda4bf6aa7325dad383cf62a9628a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "4a7e6594f390f13f042816f52406e589c508579e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d6a7049e45f2dccfc52529a679a45a8afb2030386e09521b655cdfdd7c6bf7f9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "c3a0f1bf37d35bcb191797cf8c38ae1050df8c9b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "bf25e7bfaededa7e54232d1e53289f3d3c86b7a0bc6eb5796f45e7e96de348fb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "b315ac4297dbbdf36bde6841634eb7da110b3e50"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ec040e6571d207e14135c5ecd2d04363ddb30fe5e77955b3970ca6685eb056ed"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "306e4014cbbff66ed15de398ef9fcf0542a5168b"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "e41605e2df356a486b4db7cfdb61a8c79ca3bda80f3834b188e0160054b510b1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "2cea6851b8025231e70d0c01a642345fdad348f2"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9ce59ab30fd180d0b84c089b785cda2157b6041fb65afcd5ec202e3343911a77"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "ee2891b29a99aaee505538bdedc14debaf9f0bcd"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "dd7361b9eef183123457326b655bed13914e783544bc0375e4478942e9e76896"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "fb1673af74a83baff3ed52f464cfde67b8f0f60b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "5a91a53b3e3c34d7f703b242b2092f9614f037c442d5df8bd70c5c5862aa07f7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "cc1736b0219e02abc11d9bbce629afa6b1155c51"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "24ed1989412c77797a8ddc4cc022ef1214b479d8cfaa7300f12ca29026aaef42"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "b7a698dcc7e2a6619ce872327833f23ab1d821d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "0a04cebe89ac669e629409fa0bc4772ddb06fce29c6d5c650d6e9821c0274154"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "5e26667c35468ec71241622e0679b7707a305daf"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "0cef4e7a7261c6f9b81c472a72b447afe993c7f62ebd5d41b36c77b2f85e6f8e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "88bc17125888d41635867a531d7e52b9a09c5d6a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a93567f3bd6fb9584c11bcd61f5ddd30fe5cbc30f937696b9218349650c19906"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "d7b12132e5d622beb2f743617f99551a55af7970"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "eba6e69d4e4d6f1fad6960702d0ed54815d7033f5b75c058b281692c90345907"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "6e10bb79f10d59b6026ec092f2e45c50c22d07f3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "806830efa0c2a13a1282d35b12ae652cd4ef2fe989eae8b020a21a0045a0c424"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "3c00632d1429f49ea032f3fa043d227d08bb0c24"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4c1b9332b61f5591b3a27a6cea16e0b27dda98573f3412e2bb6c2ee84ed0a97a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "b92990a554ce5394c14c7ec4c2d3ebda4ce98b5c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "aae3625e0be480b3f05250d94aa21da9c5350d0acf394739a50dfd42bf1c3470"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "a9a769fafbdb7579412ff5b070fe0a4f3fc77bbf"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ddd997ca05d0a15904d931c314aa0150690ec2c173b0411d296edbe96a15cb23"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "b8b38e551666a34be0201ee3b078eed5b748be57"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "71c0347b421aa3535e309f50dfef95365f438e3f8f5c9fe2cd9e26e9051fd3ee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "44285df4149aced249e39ada3faaa4d86dc30743"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9e49c3cd529c46b068463701f99a3fae5f9d081cbf8d272adc137fe4e0938e05"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "fddfafb9b74e8eb2b98913db00f910193244bc67"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3be5f911450719c7bd48f91176b38bfd23c3317b130cf8f14683e9216e6eae41"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "c6009cfb8bb06fb9f4ff454835c7453d06456cf2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "e4b3d705ac786f92f6aded23b81de9400865c225715237f06682cfcb6f5adf67"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "fa0b3310d1be6f788ed7495262a78939f70f7648"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "bc0fed61952316975451cc535e951c486f0d5e8b79bc2d1c527b61760cede177"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "5cffe653b95518bde6152cc1c604482a7ab04cef"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "59069cff6d7dbfc6ab0e5bfa5d9b763d5afde50e5481528259e6f306b1255677"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+1/OpenBLASHighCoreCount.v0.3.5.x86_64-apple-darwin14-libgfortran3.tar.gz"
