[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "169698cbbfb546f2dfbf425670f3e87b8e293291"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7fcd0e4d4f9c1dd77c5ef8ca7751d4192b607554ad46e60c74c8a4d6542540e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "1ec8a51bdf6755b9290a2851915a0dc26428d968"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "63145815dd8a074e69fc5bc4949f5c747eb0c03b144c3f14ac1a4e4639f15dca"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "bf52423dd6ca5c7a79a407ebd33f183218ea20e9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3223241e88d069882cf4f9b3f7430b7a5e19145df86d5ce944b9c5026901a6f9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "b39f8774f4f35f2fe0c5a2cc0dbed3c527516711"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a4b9366012c0334c74297bc88e16813f435366c973c5e9d17a86ea546392cdee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "4f651928b03fa2defefa91647780a2e92b1a9167"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "97228184f9604a91db2e550e5ef41f81ba723b02e212eba2c994034ff0270d47"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "a8e5095358023dfb0bf86202ffa4dff9f3a8b18d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "45f1d794c190ee1cf41f4a871c61d37f7c34619fc3622fd8060b385092d1d39f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "c7f1ff45989104b608f3bc8e19b8f92985d1d47e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "1b8364808670b26e339b39b6ade3f8d8546487b769f0d4653a9df3bf9a553a99"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "990241affae5a90bebab35d4eedd5f586ee63f0a"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "73f9006f436f364d317d00d7d58c0c63d365b69318dec89a3e947923b258dba1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "db3ee2024e3ea196aa4f9f3b3e04414d2375d030"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "80eccf85d1e5ea5ed0b319a0b885ae457607a2bbdd0d9b78283302c589433a93"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "59718c12c6df1034d3fc85d4c054f153da50737e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "505441cc26611ef990caff37fc0d80454fbaa37484cd01cbdc45954faa227015"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "c8ec398d774061e6385c0a7944f05538082334b1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "1ae6ad7680c56b211d0a2b436ffa358f2dd2350cb4ded42fc326cfbcf1255b72"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "c82900bef4460afb09cb8f147c147ae9dd114f53"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "8de739e9978a19e461f81dd15fdc24aa349f8285f5b2b86196d564ed3041da4d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "32e6f1ff2b294b25a3e07abf97fe051610c935a8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b943cb4175c0b94466e06659e0b9d75fab2e0f258010eb4e053eb66cf5a46b54"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "5cac7d9ec3b4b6a9401322dc18857fd2ec4f88fa"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9aec5b556a6c5142bd7ea06b646643958e02dd02ee12d1e35b194e3ecbe88893"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "dedaf2754de4561bcd1cad4cb872f9d25e0d9251"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "875082a1180f56b75dff20be7c9daee84e96038db100b8a3dcc69458898e39ec"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "46163ff49da184939c1cbc500499b69207cefb47"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6a1d1b998d93b3266d57e93c91cadd186354a3b90833bfae272c83e7b8c7eded"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "5cf678fb91dc6c5e0d6c82bbe2667cfb498b988c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cacf4596e237e8d94b1ce3f4d868c947b461f9f0b67ed5461d444e252c275751"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "eedf7b1b13ff1a91f061152d56637fb461af0d79"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "61c504607c674c8d5c65df6bbce0519cd5a12d59d5470acaf0998f8513f8c588"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "d16032804bcf034a384d2675f04b8b18574aca43"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a98a1f6a88d7db19c32defef26b71cae49aedc9624cd36fa649b8df6686071fd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "e6ef5031a3bf06c2aeadb72284696c8e60a91735"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3858c960b597b3192579553cb13cce21abb56ce4f1603abbd7c7a9e0b3d85b0d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "fd34cb7993b087015ba9ffc3be6d6c9260d530e0"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cbbf3160457dfb2c04845d5a5c63cc4c5f5eaa409240c405f09be5471ed62b0d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "979b972c4c44e0c39ec06872a5db022bdd2dc7a8"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b25c2a216ea6f862e185205b2c9c78b8dc11d2d4cf3d34f1ed62646d26704871"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "ebb1d3f7eeefd8cf18758517a0ee9c82fb7e06da"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "977b03ec56adadff999321d00e0dcdf330d085039283f183c2ead7c5b03c2eee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "92fb38db00d6658ba5996a6c868f428f3df613cd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "49439ab0e02e9b0eaf519a67e95b5327f9c7611c189cfbbb209c4d1d91e7e462"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "fb06788dcd3cc6664440564181742dab849af19a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cdc724d43683e428cad1e793237e68489b1be095326749dda41f62aa3bc9a381"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "04a38553399380214b2ecc0e9bca81d47ac590a8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "57019353c12b36080d8763396bc73d3c019f91dd728ad3707a2959cf126c95d0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "f5a55b87b225cff4c934783a6f6d913a54ea3b4a"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6b903395c2ee1baac752b5c96440a9f46f9a4b16560c17ebe5cd90d264c15561"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "496fcc9ce2913dbd0b9eda4607aef00977cd382a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b71201ca1ea2e1770d16026fab43fc5e196d697f455a7dc7033b7bc552e6e9d5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "71d6e74f7aebd68b9f584783ec85f955b3ae63f3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "66906d0db44d58db3f70dea361415bfe70550d13be49d8982668641109fa10af"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "9d9710c0a51584c3742f6705c0160fbc0ad84f3d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "82624d453f039abb13c13c0d2a8ea52ff96a4e1adfc0a66dc7bf3b7fcda1a4f9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "93a2bbeceb00093f85143ebc476b6ca3f2ffc9cf"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c786b259ce8be53728cbb33c353fdbe87e15646d2735c7ea9ea72c9d0af1cd68"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "08492aefd59c9c784ecc9d7c186859460e957396"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "8b08ddf9f0503c5232098857909b89ea57854836f53a31b2b363007e9a6c2fb9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "6791538b5d3b541849ab3a3a2f5fb37a516b1bf8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3e5e5898439052adde165ae2730a8b0fe1e06a5d78462e034cf4ca7e1efa6acb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "9be9e94f0b9a45b606f9a4b02fae00c15a5c9a3b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f74210e26b116917280631963c4728f4ac45d77039508799488f5bc05e5adfb5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "89a333a0b648215df3e78851c45e70e470355d41"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7e37770b0996ff7748c92921f8c7f9c6d79df2dd44fb24819b242b9a43cd3179"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "16c5ee4151a7c7351c09e7a582009bbbbef3b72c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4c32d2b41161ad0e9591717f95910b9350236dc3b66c2315cebed3909df93665"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "a1839367204ad1790ce1193424e2edf6557313d4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "e3739367547b897990ed6da72623936cbb7f6fb3496da51198ad49f7836eeabd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "d52b248a43b7a5d0d825bbfb8e8156f9dfd850d9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "1dc72d911d19eafda8da0dfa226226bebce6ed0b7c3f030670489ee729a98b2f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "09b30eaace689b64faa630b3a4daf9e3ca9d1297"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6a0f30b0ba605f3801f62a15ade0f398fb2022fb0376decf6045865cd3eb210b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.5+2/OpenBLASHighCoreCount.v0.3.5.x86_64-apple-darwin14-libgfortran3.tar.gz"
