[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "08763cbc7eb794bdb6fd641b80dbc182d4f600d6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "19191dd8908dd3ec51fea8ff689f3d048af75dc8c82247a402049a7b6b21a0ac"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "d209b3a1a0fa63fc45257127ef95718f2cbe1038"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "05359c280e1017c9a8ee21549c51949f68a07d6a956488672f6143fd9fa09d77"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "c79f5a311e3519d00ab92716c2277261e43ecdb5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "78b839328d660e461a1594151cce5489d2756ad295eae0dd72be5b0cc489c327"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "af1d3c742c7f91fc4b97a75b17dd0b7b52d11604"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c99c774538a3ff785d22f9f00b3a35156c6e13147fa32a256e9fa338d346aebd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "b313c44d995e51f4bb4c90308d0f72a7f22d85c2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b56a023c8f3af35ec0bd7e2f7842961c22089e476fb22ff92b8a48b9c2098453"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "e8ddd69c1e0c409c469c641c728ebf1af4f8dd42"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "55ee0adcdcd7eb57a2e18e3fa2a0dbe39e7007345de6f3b3dd2f52b1f4926adc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "16f39a71537fd719a4ea1d6cc9e6898bce7ebd41"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "950d1910a4fb27a2ccea5fcd7b3f214aebd30a24b1f58b1ddc665dcadf9a7333"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "7649f8e41b1e67f9e708f221b817fc1518bb0f6b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "71446c4825a3b40a9ad120cc290bedea91699d517cd187d358612bfd4877ba7b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "c443042ee6d66376df8d8319712ea20d5c6bdabf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "705a47f12201d3e3dbd245ae7c6b0162e84b9f6fe56de3fbf7fb843b3ff551b6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "05eb3c7bd0251fae4556324d9e87c9302347ed20"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b20f9a9675f96b1da942bfbdc40e6f917f1f0c01f6e487751d2816c4d7854281"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "5f58de78b1d8ed506dd6e384ae1fcfe3d662e901"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "aeb4ef59a6b79e69ee9def83f62c4d76c484a6c48ee37558661736290bf6c705"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "6987e27dd1b0818f25fc0153e0c1fbde9efdabff"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6089a71d826df4e8a0e26521ad8d49bd41a90a671a958f6db575979ece3c8800"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "7c2623d32a56be057f0dc85be93057d8737b2d8d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c70a7ccf34de826d9d2aaa7d6fa6180d5c508c691ef38f01705c0f863b3e7a65"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "2d3bec6aecd0101878ebf0af5c62a6fca91adaa9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7fc89f7015fac367a73b96e11127dee542215a25ee46e804918c68e843077ad2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "f640ea6efc1f3570941cfd98fb457db44b257306"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6e9e46b384e26160e7902ab3653518f243359d1f59d33d985c28c25efedfb762"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "ca767edf2c96b3623245f47e6658be4fe8549ffb"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cee7a1dd143d3b39a07f9826bccdc53fb1a52054a5cd23f0a557c1c48903640d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "cfcdd036cff1df7f2948e301a7f207c19c62e9f3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a729d6cf2fe42eeeb5139c32e14fa7af263282077bac332c2edcbf65b2dfd576"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "5a404299a56d8efda16c05d36ea0d382b824c622"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "5b4db244b16523e53197026ccfcd7419ac804fb464afe852832ce1d35a25ba2b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "bf377e7ec48d3e1959f95b9c603a2a83e440c0d4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "2692e88b64a1d17e57c46f959b6d472143b1812b464f66908d46f9f7bac78b69"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "ef03be053ff6cc99507ed259ad6c03ec7b7ab091"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "37de3001d076830cbcb43573e98d293c0829d7abee55f21a6395b81b1d33a9c5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "6ff134c9a4c98eaa7e5e829b91d68b0d49c5dde7"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c4254243f015404747ffe4402902194963d82486a4791edb89cbc671b38a8613"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "c0767850e6433535ae0af871b08cc3842d85ec75"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "36dcc57329fa0b7f5c373e9239a1cf4d741a3c1ebea5d1b1491e2215a39ec43c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "f782097759a3b4fabea68c2af2a68dc1d0996bc8"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "2cb8fab286f35d71e9e0a8d178995348575194ab9ac0f834c4a3ef6ca5247353"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "28bcd06cbab234c921ea5a7dcbe171c17764e6bb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "05cb24c10add087be8a3426dc69b5ff4b05188fb84cebc929aca5b0e7efe78b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "9cc2badd10d62dad974eccb20fd5818621c006a0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b5991d9fe9b6e9d9d92e965aaa71e425551246ca4f1aae0265361cd23b009123"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "6c2790ca94f978393eb6f76358fd6f68992b36ff"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "935e7474fe60fd85f18115b32b5e62b7d73f2e0f1bf2fbbb11ceda4e545f2703"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "48007b28b0745f07972bd3920b264d60c326694a"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "247a85dfd18f204db9f7463763a3c4e6595e430f369133b4ea7953a91082bb75"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "83e19c90a7201ed3276110e57ceb9c1c634fe67c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "af16b3dcdc0c5dfb6e5a4305c910ec5997c4f10d0afc0c89f28446eb321b1f48"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "dd2275652fe792e0d95880fd6d9704868752f93b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "87a9a0270f13a534d180dc2fea65d6f962d6a91644e396b8b5e14e380af1be4a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "2e6e5cd848c557f03026710bc97a889aa2870765"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "83900a64f54edfb4acc31fca3d636f99fd4c30a7d7a62197f358857f09df7a64"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "75d4a20d9a7bf5834d37c401e3ff86d9fe3f9c19"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "23e953248f47b6cf3f3a5811cebdbc82fb7ce85d10571751ad7eb0e5b4927a4a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "5be803201686e998ded806e06e774bb6021b5107"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4bfbc58b72852a84f81e08f08bb5eccf1815adeb175aef8987f9c35a66588348"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "50b02fca85777f4f23fe6a20032323703e89223f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "dd4d9294a2296396fb9bf3eba88e385d9d6d840a2ea66b52175a38f6a49066f9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "e4c9d9ff54e788eb0773fe21c1a2f3abab90b743"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7ffea03b8b6f84451c1ecabb4c4d20c01dc8e4bbe22071802d8662ba621c9a8f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "5d59bb72aa3291123b6bd2b36aa2c6298b328f05"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cd8f28671fa7ab273ef6ee23fa4dc106db6e9f06ee683dadd0a0aeb416d1b5f4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "0ec85f9da2bf0a0a7e81fd510a549d23d8ef9af0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "0d36d3641c282a004df4f5cf50dccf23e9d71b8e30e776375c1351d2aaa8e481"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "8597a0889461669a1e5bdc58065f633cc6b3a7c3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f4f65280b7d4586e68ffd3758eb2aa720c3d4930c19fcd422cedb7deb641443d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "3773d74a07c2f7985d28dd277cf475483151bef4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "042df392905c38c6342628ca85658c0a21f1d908f1f28e33edfdf2295acb7e97"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "41868fef228cf7d924c21801afcf11bc74e674cb"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6d057ebf2bb4da805ccc8027731ed7548c66f2836d9ba2f73b49d59469e8c6ae"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+3/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran3.tar.gz"
