[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "526d0de7ac53b491252fc49e09addb59725b4a28"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ec27bed3aaf559b63ec7d976f09ee3d0281baecee17f97bd4586fd072f224f18"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "24848f79e1e56b3c711c7df82e2d261607ee0dc9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cfcb508dd06c66901dff6b68ced59ed47fe86c787fc96ad3cbdd1a32d55c0211"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "986101ee9ddb2e13a06f1428cede22472a3dc09b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "18ecc03f0d5594b7d2af008d88e85a1d215fbc6014dcff3bd0399cf78b5c87dc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "1ffbffc3b1237cd14aaa5b01d505a59d64310620"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4cdd94d9d2ae9e6be873ab3380171897033e30860e800ea6658e63e44792089d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "62e69eb552b59c4b003e85abf86266f7ee0fa32f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d25eb50f479eb7acb446096b9e2af1b9ac1feb50fa18dc8559c0d597bcec0267"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "f0597e0b357e7c1bbd99a03046d51b736157a4cf"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b36658bc30ec8c5e8801ce2ae385eb4a733fbc8886b9f4d395ea2a2113b40919"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "425a3c74901b181c215e4bc59ea9cbf180aef7e7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d7056cc6671df849911346acbcd66f77443dc74022b731f5fbdd3ac620f7ce91"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e433e0ed94d4ab3040d7649b3520cc96fc6df101"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a846995db41e598bd73f73396c34e2c6f1261d4d89b19e4bf41b73708eb13085"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5c20f4e2611acc9e8fbb8c8ff788443f8ac64551"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b86b2f28d0be72937f544bd7e6d5edff49cc0ceb48be6604d6bc8022e5cc9f9c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "beb501ef97d9b3a0c8418288c48460eb19bb1cb7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "bbcc7d1bc6779c348b2771ee8c470b2f604a29c3c574b3f9ead47984eeebdd8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eda0109d2f16af25e8998ffcf6588aefa3f1a169"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "16e0429949b6b3e02b2f2b9e2b1c8dacf0af50a510c984c517e0c83838053906"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f634da1bfa04cdde176df884eb471299023a7208"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "eac4f08974dff1f5816e26c0c03ee0a6aa9ad2932eb9d555e8a663f04826a399"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "76be9f71474cfb4bd4d06f5b7416801b943e98d4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "fe5abb2dc20286511bb9482b07c7e1c951ad2c25b24b46d445357bdbf51eff33"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "8e76a8abddb9cef4384688ba62b1b2e616083ba5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "05d1200acbd535f5960c52abfc3182ac24598ecc17e0cad5a2d78e8eb3dd365a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "6925c4d72ab9fa46a31d0ed28c7ca22f29ee557d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7f10a2fa325f2cd8789dd1e911e2b7351664957fd993be54b0455f4ff957ea3a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "e346501b7af7e7ff79d96a67da070382ecec6830"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "42b226fbc245b4ffb0405b61727c6c5db6a033fa31d56abd49a1855d553e55f7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "2504801ff7f096e15022071eef6884b06a6ebd3e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "dbf32912a13e8ea87395586d9705f2f196ead9b524fd4ff4a972f0b21d346aee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "3b1920ac6e112a1d6114b6bd8c9b0669170592d0"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6f7c908b30c5e6fdcf8df949223e542df23f0ee16ef8dcf0c2e210be3324892d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "95a411c3f09cdea93cbcea10fc585ba105cceddf"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4c357f05ccde52db28605e8fe62a87074b9c04745dc4d3eb558fe4d40074b100"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "6bb88390f21fae348327daab5bf7b3a40d42efa3"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a17d3ce46c877ed7854c8109eb289a3a932ba035148fd306492325885211e4b8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "806252e72940cb2fbaa6c598198b452eea3186ef"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6d18efd930fd6d3511a5b52927cb1c26cca553562ebf4e84802b5dcfa9ea4d73"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "9434de569e559bbfd238c814d7284a0471a4c3a7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b0ca9ee22c57c4744c35636c4d88acd6d99526454688517a27a7e2adea2804f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "349c83a1f8debfd0324a0ac1cbc1555f1e134ea4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "422b40494a464f8f38dea85b2de03f7b5fdc7f166667775c2a84bbe5a3be0240"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "9ee0334b2ff45f6dfd41d281e3b9e616ea4728b2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f3ebf975c3a4b42e7fcfc27cfdf0326c667833e3b24b6ae0679245eb78356ff6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "2dc5b93e3e0b259f3d8e4548f6f52cd3ce852e7b"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d0456e66cf3a8de5d2cb5302ba23f4ae929dec58c58c1479356b5913e2086c64"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-apple-darwin-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "68c906ed8ea65455131a700e983b67ad7f1fd705"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cb94938c6da9748f6a9fc6cbb664d34d9019bb711c7c234c4b55a023221ab52f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-apple-darwin-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "844d12031d94ad799258f25c14acc1a693bf6a3e"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3531188df0b36ed0b3bba55ef189c65b1f60f2dbee1dea54c922a709586c7dab"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "b49a245f05d9de382b91864c9f886c73d9c39edc"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "406c78ce40e9d4f0dabc7a3d5d783767b1c0ee6bd20bacbda5e4ed3c3112abda"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "b6827deef779e4197eec87464295d52d0a3c16bc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "806c635bd7523ab832db0e41a632d82f453e9161c71d7a77cac9cd95e25a6997"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "7a0a9654f020a647a633a45db0a8f9c6d0b65129"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "2666590561ef0ce7bd8eedcc6f59dca786cb709689bd69ce258a15a2695259c7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "fdda74c009e0e979c0e026128501d75d98f43ff1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "27d2aa39a5748a7ea2362db3cccd8d15764879ceb9cf6bcb771881baf6b7753d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "62c212adec1ca2b65098a51c04deabfd76f0d7ef"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ff201d07a3fb80ab1d75f053ac645abef7266f36c620594c8ba646aec6b385a6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "0c9704053cdf2b81abb922ceb4606b8c01460bdd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a1239358979f13e58d162c37e83d911e65c4b3c7f4c3454757e5c512a871fa5c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "073d983570485245ef1138428949f668420320f1"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6ff4674b4a53992130e6f961a9abf107ce2181cc823587d9eac09d4d0482626c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "cff85864f1cabd04f2e2b9d92680eabf17c964e0"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "20fb479dfdc8add597b56760d010841ad66c24ccda6c89fae7625ff3455a686a"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "10c194966f9b230bd590edafa307a36a447e76df"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "71920ecc9a1b16c81be8954f1b10e7eb5df8325ede74c8686484f78661635c7b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "0b741c5282a6caf6be90e36f0d8561a8902af7b7"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9f992dd8905df745f8094402269be5e8464813eddd94f5440e21ecbb96a62496"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "effb91db81ddfd5a2c33421a3a0ef88127d25c9a"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "34732261ba134610a19a3be930ca52eee61b6420ef23af0012b688e4dcbfe215"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "1c5ee623d7f42333f01e0c98ca726fc69ba2ae4f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "2ab16bd5c76a531a6d4719ba4a8c4958048fce5b777c576dec2722981a1e57aa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.10+0/OpenBLASHighCoreCount.v0.3.10.x86_64-w64-mingw32-libgfortran5.tar.gz"
