[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "33c19fa0aac6b3336f6fdd1e243e02219d51b109"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "8a2bc4166d4176f5adc645baaea56a2bd517da88e129e705dba0be1bb76b4ca8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "b2c7b16561a6b7dc2eb3b0fa29f7c042f1ccc42e"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "1ff693493051583a59f58e9936d2f31024035c4b7137d82c4db6a03e706b0b69"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "78531faafed7f336700d549a0a5c829b06a39b14"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b3d0780ceddf4cd03c7b37eac4f12e0a8324639f3a7d04b705bf44022dcd5791"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "dd338ae312468c96478400d72c3828415a7bf984"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "43344457f3325a36dfc405a45aa057aa728a8519cb9c16853808e9c9feb993bf"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "729c36edf5e160ac8e515aec1b2f16f3daa7cc20"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f5775ad0a41a795c0492858f4082e4a9dd66fda68cb115b8651a0a6733d6c8ab"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "4b01e513a452e4cc39cabace1f9f30a92fba6c3d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c90395449b2e6efe1af309e005dab8e628d99293281a0444bbb0baf34fac202f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "41af4364076a91583ab0553b1c8f0d231dac3741"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "67d4cb6e770cfa1c8537ce98d503cc5dfe81df5b193672c4fd7174118d521c3f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "7cd0621b1043b8a1a6cb7b6131bd650856772d17"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "cfd18b109ce76b5d74b470b0814938850b81bdb1bb470c0fcaedcd7c764b8de6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "f1ced657e88ce61237e5d3ebcae63dcfd00990aa"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7476f66ce14c26d6fa439bd7d029017f9ee74a36c955384d598d21b133eee635"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "991cce9ad9cc810b7a1e0ac25d3f4f059ccb68cf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "08e3b3d6b670c9fe6ba5bb2cefd11fcf3e70e2d36322dfa0d6ea4a111440084c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "a2f7c751589df3de67e9ef171587c1dc830f6dd4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "2f95c415caa2a183236a25796b20b11f15b511472318136c3f0f5cee95101e69"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "c3d7166a2430b79284f2f75a966eeb3769dfa987"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "fa5ee5d989b715eaef61de9e3cef4f14f0b8ed292b7652c426bc965f93ac6be1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "a22effa110ae77b9f47f06704272270cb6fb1e1f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "0f746f4d6b98d81ac6d697f1f3b8465663365e20c4f525a03876684def04804c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "3dfb6270acf7cce792d38252263adc7412544d77"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d56d81db9eef6dfc2ed4937dd5ff7c151590ebb2dff249b8644e3455ba2823e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "c2194d2e718f87febd9342b9281591a17404bc00"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7e38517af8f7d3d76ddd588f07dc071d016a5ccc861e0806f8bcf68e4481a716"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "d2ff0291d19c1d29f0f8cb28315c48be4522d7be"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ee6504c8553264a9b98938fe3a7acbaaae5ba2a214a47dca88dd30a5f8e547f3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "78101b8052a1bd05fd6271c84330c2490d831d1e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b58319b6ee621676e2627603d003d5b01aafd6d91dec8143e15e926397bec663"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "7637d7ab6650915d703a38c04b5a3a0b006e8c6a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "39cfb12dd19213a1f7f8377fb0592bee604de64104e27c66f6dcfbaaf60ca89c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "6f6cd2ff7363df90cdc6d8a2f536a284e1848841"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "8eae93028a18d24934dcdbca7e08fc1f4c9bba1c0ea8585a07c9264979b2d950"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "2dcf1f66962f176e2e15aa3f4c0f64d24f7b760c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a82f75dd56e2ea2e7c477f5dce827d72bb55084cd4793be3ea79cb2bb6958db9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "edff3872c2499fce691bd5aa58d6c7facf5ef753"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "341b7c994bbb7d41430d20e7a3bc53e720a3fb68459c2a02e2e2270bc8787133"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "402c0862a6bdac66bda616751215d5c6f5b93f26"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "0b5391128b9dfe1daa8c80055d22be56d9652035e30cd6dc4825a694ecf58036"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "75f31802c4f6903c7b0a8472958ce270010ad283"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "6972b96ce7ce2fcd6884a7234736494a283c11362c5066b242a601f3455e4620"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "6338fec2b3f38e7f99259d3b9eae2571bdcab19d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "44a5842f6811028f933faf2b408a7d58f9936c3a52d4fca086da131f7048b263"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "af6c8ada56cddf91b65d94fc2ae55c6d96cc4974"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f6c1456ca912c3f108b370a0018d24ebe3d7ea47da3e9f92ac6323950f90aa96"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "84b96e7bba317c395927e2906647a52360dd1510"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a9f3c2c711d3324fc42121e0db3c3410c794127bb8cb07ef0082709e8142bb77"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "6e3d6c8d271d60e746379011c4081d8dfc5f2762"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "e7c4afaaad9c8f4d32928180619f4a6a3ea25a058777b780662dfe8d98362bc5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "755b684a4d3101cb0eaafd8fab15cf498bc702a2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "aa38848883d296fa13733eb6556fa7ca6da86c17130a979eec3b69899b432a34"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "5aaffa09db2538437cf622d66205249928f39a5f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "aa03f34547b7fd5325851adf619c3e34a1c67090ed44b8e22b9e6ce68d8b5197"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "8e962551e95c6f1535b548665732d2061c756d99"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "1b45453b7bc9912ca1af75c13ef01c30dc89681f2138f2e136a40071ff1f85ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "e28ee58ecc30110cbff1bb1e878f94ee68925b08"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "92b537fe3b95d765248757bb583f989c8dd5840c3abbbc9a163c12aa5120939e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "25dd8cd413db4791c914a526228bf3eb37e92bde"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c440428c8b577c44d6de27d08a8c384488613b6ada2f857cc6d6d6bc669d84bb"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "607cbb15b93cbb5b7763a50fb0022fae62bec8ea"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c0c0e640ae596720cc506191ea25f852cbe25d82a5f3878bac4ef5c003f462b3"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "2b4ed2c8cd77613e45852c0e8cc3043e8197dd91"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "337db26f476c781d4d6e727255d711d2f4303e85ebd1ff62860b986c9474daad"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "641cc7ec4e5d22e84fd66fac96cffa33b075c27a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "923745951b26d7eebd77d716aa46e1fbe533ec0fc81c6372f5508118c1b926c1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "c5194773476c8c278f88b61ddb27ad467c0fa214"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "db2ce926df42d110dd22ea733c334dfd912baea10704acfe16fe6b61c2013e43"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "f5aee0ec2c32e82b3b219c1f6721380645d7a3d3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9309f0616d73b31b89a9edb8c9a8a15203c3d83677e80a37aec78dbdc4c61581"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "1dca6274da2cbf337b60febaac13bed74ed68b51"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "8490e934bc7abf64e233b3aeedbcd1b0b11c6ae9b1ae8acd210ffe61de05a171"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "8fd10b25e38d0de8fed4dd1e40bdd9de317f0253"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "32d0299cf601e41aaec6f07d8e63a92d7f3ac6f0cdd511bab7dbe86c91dd5e70"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+0/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
