[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "daf0f28845b4e5b3cff6b9e91c36930dd5a7b0bd"
libgfortran_version = "3.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ba8b44ca2f7665ffeeae4df13298e1a0047622df7b9fc7320d4d936fc14949ae"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "d4da29428be4bfc291a6c3416ece251256f5d47d"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "efff17ca455c5d138c054c16e4d7d004b4a5070950e0a37801d4171f077cd68f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "82840927576be1ff9078bf698c0c95e665b17cf2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9ae0aeaaea00251a984145060ddf1761d0975ec5f72a9b0272395711a61c1d3b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "d9c81f6bcb6dae759d11d5ea2135850533f23dc5"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3b76b375789dcc350c1b5adbcfc1a309202a391c6b09e8ad640f3b28c78a05ee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "57ea7eb13bbc7674fd65b3a8d23bafe70d7a05d3"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "c18c6eda25b3806b6e573d32789036207bfd4adf12349f29ebd0cf01cff5ea62"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "acac104cb98913d717647d59dd66797ffcdd78ac"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "4bcc6405ae692de7fdc703a673b866996e78f84419411f3d764036ed26a4c196"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "3d96b00bca9a3abb12f482ec3db8d333d5b433af"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "48895279f35016c091221054bbba54193308eaa0d211f7bddf0ffab425353154"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "158ebca156d1e7d8d39ad1dbf20402e7edb98ff8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "19f7fd20cab28fac0e309b461dfc60655e47bd3dc0b6a57385998cc86e8e70ea"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "457da11505bf6ba8baab748ee0b6d0b5823e6ad0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "26e3cb1e2398673e6470f6391be4ed262a874680648e7672e24e11b4be191b93"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "f8a5d61d00930ccc28389eb104b2bb3efa923489"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "605e0a66319a4d28cfd287345f55b7f5fe43f067a251c8c8d1245033af67ea93"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "75eda1c566f5f33cc494e4a5cc0d47ce929584ca"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "83fef27322ba261743cf05ae205adbf58dd00d7adb94188d2d8edeca78c7da35"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "a62be55b0f8771ce99597a7a928567a9474867c0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "de7a8981210066192466b5d347ffea4e821ff657d3db7cbe920b0f93dbec64b4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "40eafec8e6959f764b5dacaedff62bb34b203030"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "36b1f5e06c8e13eb89f14fd05f0f816115659c7b7ec1b66b36f0af4319708d8b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "34afc10778d789fe7e33b2755d446fc48e815701"
libgfortran_version = "4.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ceaed376476589da15114eaa2eba1c547e4a320eea4f1ee8c6baf8bf876de2c9"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "1d5ae6e4187e40d5652170ca4f87148e8d12bdc5"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "125a7181c940d8a4ca769dbdc0d9d487c00236a9947fa7bf021194463530dacc"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "58d749ed8d2dd5c1194f9577ff6d13e5fc94ee96"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "84c6a11ddba815338588d77bcaf6f21681a16bfd4ee55f8ae22bdb4fe19a235b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "b8c75e27eed0a3ec7d7c44b44a213de31a107ef9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "a2892772395ee154b6b1a16bae1eb984802cc543f91800cc6cf93ca531f25dbd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "a72edb3c6627edb818dab1b35353bab750424274"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "b15e965a7f6faf1cf22bd3ea32d5636895b96284b0c6a5e3109e2299ec351d52"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "453aafcab87c365880271a9cd24981902bffd401"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f1463fb16f59eb60176804badc072441f2ecddce4b284dd1d8914939a9b3812c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "536e516074cbc5445b3566a47acf21d86ca56f7a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "e7d50422d0b742bb3226f1183030a9a0af8970a9bd625e50ecee85ce0a1dccd4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "2b0eceed37722645ee2d4df731231235d90978e5"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "2523b876ff5c5993b891835b3643d57b2a09d53f56276a9faa36b07779fdf204"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "b4f2343c6575a04ee10e2ccca59593ad8aeb0021"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "243e6e32d2aed51303ca349fa8177f8e4266e08d10744494fea83eef7d817325"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "0a49ad873f6eca005e99949d499c627509bc036d"
libgfortran_version = "4.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "31383edada0472f46fb56cd8b85cab23b8455e02b6f7a2a7df93b178790db6a5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "armv7l"
git-tree-sha1 = "90e672192a1d081789e4c5724782039c9460ae59"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "f20d2c3ae3454223094048d73e5f0897c79a35657ed6f95b0ab84b78a5fe8cd1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "da08650fcc06c48571b114cd2ebdf367cee82210"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "58af9742955bf885eda166df2c82ecc55ee1e9443e08250c27c1cca90db5d9be"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "5276a1fdf03e5e33d24c4bda350d20c1d6b001cc"
libgfortran_version = "3.0.0"
os = "windows"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "7a9835a5994e570b56ea7188214775f512647fde995fffb0d8ede13e56d7a205"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "1fd0eba49f9b76b78c29976d00377fcb2358a7de"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "48373e9a72bd65e9aff87df926bc6425f63492014ad01b54d6e4363e96f05cc4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "powerpc64le"
git-tree-sha1 = "1e48d411cc6cd86d4527d54f19f0e2d9bc8b01dd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d16b88d47500240d04e7e61031ff599c3cd787c05af87bbe9ddf24da0e2fdc25"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "8d51a6c85c53cb45d16a827daa8bba4cb3c908ce"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ee65a22f83647ab587b37462767b87504ec6cf5cb0f5a415d26fa596408342e5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "e7e8e4a1536cfa88b93ef83795dfde9ca0b3c88f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "3805dd133faa3b2117dd382460a9c8d9459d807321b62a0c8aca9450a66d61f8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "cb24f1946b96129829aec95835a5db6481771857"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "28a968737084f9acd45fe6e586328c9f238ef066193b0d00f514d8d6b39e9d73"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "e97aa345f2c9f8808f9b0466f9180465718d209d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "dbe80dec63bb415da03160fbee4d42becac475344365d1f19f1ba9caf78202c7"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "i686"
git-tree-sha1 = "cc8832c3ad73f7210cec51919e3eb2e265c70810"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "5faac1a130280c2498a9df881072d982b2b0c870fdcd140b1a116c0801215bb4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "2f06fc48d43a667440319c15ed810f139321cf4d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "9b3c13636edf43211f86c89864662b5f0da3716082acacdda4223d1b087ee3f0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "2be56c66e7d3df5b7c23654b3dc317b8b4a6c122"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "d5df13d99942d6330aac783bc45bae2080fd23ab6797f1a072c7e802d0044587"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran3.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "1c1dd561379cc5769da1acf8cd969eadf7175421"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "aaebd30b22db15faa5ab1aeb36fa15c34a433bcbb3228471e4f51905ee819ff2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "aarch64"
git-tree-sha1 = "2b78015cb78c7947abe2b418c64b8f7cae4cd7ac"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "ee66fa9290ecb6e7bc6b103dd55734e406532fbb163f1c596b3da8b5680bf93b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.aarch64-linux-musl-libgfortran4.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "249f9c6749967fe441c04f9036d23c5fe8503114"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "da9aaa6e6ec5ec6876343fa1ffbb1efe1da08d86c470437c921b555411424803"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[OpenBLASHighCoreCount]]
arch = "x86_64"
git-tree-sha1 = "f503207f2f6c9593a44d8bc22c769fa81245d034"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[OpenBLASHighCoreCount.download]]
    sha256 = "43065cdebecce128105551b587b5b97ae2f97c14de503a72bb0fc1a0dfeeb896"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLASHighCoreCount_jll.jl/releases/download/OpenBLASHighCoreCount-v0.3.7+1/OpenBLASHighCoreCount.v0.3.7.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
